n = input('Digite algo:')
print('O tipo primitivo de {} é:'.format(n), type(n))
print('{} É numérico?'.format(n), n.isnumeric())
print('{} É alfabético?'.format(n), n.isalpha())
print('{} É alfanumérico?'.format(n), n.isalnum())
print('{} É ASCII?'.format(n), n.isascii())
print('{} É decimal?'.format(n), n.isdecimal())
print('{} É digito?'.format(n), n.isdigit())
print('{} É um identificador?'. format(n), n.isidentifier())
print('{} Só tem letra minuscula?'.format(n), n.islower())
print('{} Pode printar?'.format(n), n.isprintable())
print('{} Só tem espaço?'.format(n), n.isspace())
print('{} É um título?'.format(n), n.istitle())
print('{} Só tem letra maiúscula?'.format(n), n.isupper())
